name: CI/CD Pipeline
on:
  push:
    branches: [main]

jobs:
  build_and_test:
    name: Rust backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      # - run: git pull origin main
      - run: cargo build --verbose

  deploy:
    name: Deploy to EC2
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Setup ssh key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to Ec2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@<EC2-IP> \
          'cd /test-server && git pull && nohup cargo run > output.log 2>&1 &'
