name: CI/CD Pipeline
on:
  push:
    branches: [main]

jobs:
  build_and_test:
    name: Rust backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - run: cargo build --verbose

      - run: cargo test --verbose
      - run: cargo run

  deploy:
    name: Deploy to EC2
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Setup ssh key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to Ec2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem sourav@18.212.169.44 'cd /app && git pull && cargo run'
